#!/bin/bash
#SBATCH -J hakbaba_s10
#SBATCH --mail-type=ALL
#SBATCH --mail-user=adam.rork@uconn.edu
#SBATCH -o %x.o%j
#SBATCH -e %x.e%j
#SBATCH -p general
#SBATCH -q general
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -c 16
#SBATCH --mem=64G
#SBATCH -t 48:00:00

## description & notes ##
#
# Generate a Mana report for the dRNA control data.
# Note that we had to install some dependencies via conda.
# Also note that Mana seems broken at the consensus generation step.
#

## settings & env variables ##
#
# I installed core libraries via conda (v25.3.1) using:
#
# conda create -n manaEnv
# conda activate manaEnv
#
# conda install -c bioconda pysam=0.15.4 pysamstats=1.1.2
# conda install -c conda-forge pandas=1.3.5 tabulate=0.9.0 r-ggpubr=0.6.0 r-svglite=2.1.3
#
# The manaEnv environment was active as I submitted this script via sbatch.
#
# Miniconda installer sha256sum = 53a86109463cfd70ba7acab396d416e623012914eee004729e1ecd6fe94e8c69
#
module load bcftools/1.19
module load bedtools/2.29.0
module load minimap2/2.28
module load samtools/1.19.2

CONTROL_DATA='/core/cbc/core_projects/2025/hakbaba2025/results/04_read_mapping/control'
EXTRACTED_DATA='/core/cbc/core_projects/2025/hakbaba2025/results/04_read_mapping/extracted'
OUTDIR='/core/cbc/core_projects/2025/hakbaba2025/results/06_summary_statistics/mana'
REFERENCE_DIR='/core/cbc/core_projects/2025/hakbaba2025/meta'
#

# Export the conda packages we have installed for later reinstallation if necessary. #
conda list --export > /core/cbc/core_projects/2025/hakbaba2025/conda_metadata/manaEnv.txt

## begin analysis ##

# It's much easier to run this script if we do so from the Mana directory itself.
cd /home/FCAM/arork/software/Mana/

# Run Mana on the "control" mapped dRNA data and save the intermediate results.
python3 mana.py -b "$CONTROL_DATA"/control_mapped.bam -f "$REFERENCE_DIR"/template_UtoT.fasta --mrna -o "$OUTDIR"/control/
if [[ -d .mana ]] ; then mv .mana "$OUTDIR"/control/intermediate_results ; fi

# Run Mana on the "extracted" mapped dRNA data and save the intermediate results.
python3 mana.py -b "$EXTRACTED_DATA"/extracted_mapped.bam -f "$REFERENCE_DIR"/template_UtoT.fasta --mrna -o "$OUTDIR"/extracted/
if [[ -d .mana ]] ; then mv .mana "$OUTDIR"/extracted/intermediate_results ; fi

